version: '3'
services:
  web:
    build: .
    command: ["npx", "nodemon", "-L", "--watch", "src", "src/app.js"]
    environment:
      - NODE_ENV=development
      - API_PORT=80
      - API_ENDPOINT=http://localhost:3000
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 80:80
    container_name: craft-folio-gotchi-web
  webpack:
    build: .
    command: ["npm", "run", "bundle:watch"]
    environment:
      - NODE_ENV=development
      - API_ENDPOINT=http://localhost:3000
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    container_name: craft-folio-gotchi-web-webpack
