---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: craft-folio-gotchi-web
  labels:
    name: craft-folio-gotchi-web
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: craft-folio-gotchi-web
    spec:
      containers:
      - name: craft-folio-gotchi-web
        imagePullPolicy: Always
        image: gcr.io/craft-folio-gotchi-207711/web:latest
        resources:
          requests:
            cpu: "50m"
          limits:
            cpu: "150m"
        ports:
        - containerPort: 80
          name: http
        env:
        - name: NODE_ENV
          value: production
        - name: API_PORT
          value: '80'
        - name: API_ENDPOINT
          value: http://35.198.0.131
